Change folder structure
suda/tool-bar pull request #327
Opened 2020-10-29 21:36 UTC by idleberg

I understand these changes are highly subjective, so please let me explain. The current folder structure is ambiguous about which files are meant for editing. So here is what I did:

- rename `lib/` to `src/` as this is a very common pattern
- rename `dist/` to `lib/` as this a common pattern with Atom packages

It's a little change, but I expect it to make it easier for potential contributors to find their way around.

PS: No offence if you don't agree 😅

2020-10-29 21:41 UTC, ericcornelissen commented
I definitely agree with the lib to src renaming. The dist to lib is fine with me, but dist is clear as well in my opinion and not uncommon in my experience.

2020-10-29 21:52 UTC, idleberg commented
> The dist to lib is fine with me, but dist is clear as well in my opinion and not uncommon in my experience.

That's true, both are very clear and common. I guess what I was trying to refer to is that the official package generator uses `lib/`.

I will follow with whatever the majority agrees on and edit/undo those commits, if necessary.

2020-10-29 22:21 UTC, aminya requested changes
Please keep dist as is. That's more clear and widely used by most of the tools.

2020-10-29 23:09 UTC, aminya commented on package.json
> +    "debug": "npm run clean && shx cp -r src lib && env NODE_ENV=development env BABEL_ENV=development babel lib --out-dir lib",
```suggestion
    "clean": "shx rm -rf dist",
    "debug": "npm run clean && shx cp -r src dist && env NODE_ENV=development env BABEL_ENV=development babel lib --out-dir dist",
```

2020-10-29 23:09 UTC, aminya commented on package.json
> +    "build-commit": "build-commit -o lib",
```suggestion
    "build-commit": "build-commit -o dist",
```

2020-10-30 00:08 UTC, aminya approved these changes

2020-11-04 11:02 UTC, ericcornelissen commented on rollup.config.js
>      // Rollup lib
For consistency this should be updated to `// Rollup src`

```suggestion
    // Rollup src
```

2020-11-04 11:10 UTC, merged